# Two boxes with static ips.
# Each can see the other by name:
# from within snooker, "ping billiards.vagrant.dev" works.

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/wily64"

  config.vm.define "snooker" do |machine|
    config.vm.hostname = "snooker.vagrant.dev"
    config.vm.network :private_network, ip: "192.168.0.42"
  end

  config.vm.define "billiards" do |machine|
    config.vm.hostname = "billiards.vagrant.dev"
    config.vm.network :private_network, ip: "192.168.0.43"
  end
end
